name: Codacy Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # By default it will analyze the repo directory "."
          upload: true
          verbose: true
